// Vehicle models database for the Saudi market
// Key = manufacturer value used in the form

export const vehicleModels: Record<string, { en: string; ar: string }[]> = {
  toyota: [
    { en: "Camry", ar: "كامري" },
    { en: "Corolla", ar: "كورولا" },
    { en: "Land Cruiser", ar: "لاندكروزر" },
    { en: "Hilux", ar: "هايلكس" },
    { en: "RAV4", ar: "راف فور" },
    { en: "Fortuner", ar: "فورتشنر" },
    { en: "Avalon", ar: "أفالون" },
    { en: "Yaris", ar: "يارس" },
    { en: "Rush", ar: "راش" },
    { en: "Prado", ar: "برادو" },
    { en: "FJ Cruiser", ar: "إف جي كروزر" },
    { en: "Innova", ar: "إنوفا" },
    { en: "Granvia", ar: "غرانفيا" },
    { en: "C-HR", ar: "سي إتش آر" },
    { en: "Crown", ar: "كراون" },
    { en: "Supra", ar: "سوبرا" },
  ],
  hyundai: [
    { en: "Accent", ar: "أكسنت" },
    { en: "Elantra", ar: "إلنترا" },
    { en: "Sonata", ar: "سوناتا" },
    { en: "Tucson", ar: "توسان" },
    { en: "Santa Fe", ar: "سنتافي" },
    { en: "Creta", ar: "كريتا" },
    { en: "Azera", ar: "أزيرا" },
    { en: "Palisade", ar: "باليسيد" },
    { en: "Veloster", ar: "فيلوستر" },
    { en: "Staria", ar: "ستاريا" },
    { en: "Venue", ar: "فينيو" },
    { en: "Kona", ar: "كونا" },
    { en: "i10", ar: "آي 10" },
    { en: "i20", ar: "آي 20" },
  ],
  kia: [
    { en: "Cerato", ar: "سيراتو" },
    { en: "Sportage", ar: "سبورتاج" },
    { en: "Sorento", ar: "سورينتو" },
    { en: "K5", ar: "كيه 5" },
    { en: "Seltos", ar: "سيلتوس" },
    { en: "Carnival", ar: "كرنفال" },
    { en: "Pegas", ar: "بيغاس" },
    { en: "Rio", ar: "ريو" },
    { en: "Telluride", ar: "تيلورايد" },
    { en: "Stinger", ar: "ستينغر" },
    { en: "Soul", ar: "سول" },
    { en: "EV6", ar: "إي في 6" },
    { en: "Niro", ar: "نيرو" },
  ],
  nissan: [
    { en: "Altima", ar: "ألتيما" },
    { en: "Patrol", ar: "باترول" },
    { en: "Sunny", ar: "صني" },
    { en: "X-Trail", ar: "إكس تريل" },
    { en: "Pathfinder", ar: "باثفايندر" },
    { en: "Kicks", ar: "كيكس" },
    { en: "Sentra", ar: "سنترا" },
    { en: "Maxima", ar: "ماكسيما" },
    { en: "Navara", ar: "نافارا" },
    { en: "Z", ar: "زد" },
    { en: "Urvan", ar: "أورفان" },
  ],
  chevrolet: [
    { en: "Tahoe", ar: "تاهو" },
    { en: "Suburban", ar: "سوبربان" },
    { en: "Silverado", ar: "سيلفرادو" },
    { en: "Traverse", ar: "ترافيرس" },
    { en: "Equinox", ar: "إيكونوكس" },
    { en: "Malibu", ar: "ماليبو" },
    { en: "Trailblazer", ar: "تريل بليزر" },
    { en: "Captiva", ar: "كابتيفا" },
    { en: "Groove", ar: "غروف" },
    { en: "Camaro", ar: "كمارو" },
    { en: "Corvette", ar: "كورفيت" },
  ],
  ford: [
    { en: "Explorer", ar: "إكسبلورر" },
    { en: "Expedition", ar: "إكسبديشن" },
    { en: "Taurus", ar: "تورس" },
    { en: "Edge", ar: "إيدج" },
    { en: "Bronco", ar: "برونكو" },
    { en: "Escape", ar: "إسكيب" },
    { en: "Ranger", ar: "رينجر" },
    { en: "F-150", ar: "إف 150" },
    { en: "Territory", ar: "تيريتوري" },
    { en: "Mustang", ar: "موستنج" },
  ],
  honda: [
    { en: "Accord", ar: "أكورد" },
    { en: "Civic", ar: "سيفيك" },
    { en: "CR-V", ar: "سي آر في" },
    { en: "HR-V", ar: "إتش آر في" },
    { en: "Pilot", ar: "بايلوت" },
    { en: "City", ar: "سيتي" },
  ],
  mazda: [
    { en: "Mazda 3", ar: "مازدا 3" },
    { en: "Mazda 6", ar: "مازدا 6" },
    { en: "CX-5", ar: "سي إكس 5" },
    { en: "CX-9", ar: "سي إكس 9" },
    { en: "CX-30", ar: "سي إكس 30" },
    { en: "CX-50", ar: "سي إكس 50" },
    { en: "MX-5", ar: "إم إكس 5" },
  ],
  bmw: [
    { en: "3 Series", ar: "الفئة 3" },
    { en: "5 Series", ar: "الفئة 5" },
    { en: "7 Series", ar: "الفئة 7" },
    { en: "X1", ar: "إكس 1" },
    { en: "X3", ar: "إكس 3" },
    { en: "X5", ar: "إكس 5" },
    { en: "X7", ar: "إكس 7" },
    { en: "X6", ar: "إكس 6" },
    { en: "4 Series", ar: "الفئة 4" },
    { en: "8 Series", ar: "الفئة 8" },
    { en: "iX", ar: "آي إكس" },
    { en: "i4", ar: "آي 4" },
    { en: "M3", ar: "إم 3" },
    { en: "M5", ar: "إم 5" },
  ],
  mercedes: [
    { en: "C-Class", ar: "الفئة سي" },
    { en: "E-Class", ar: "الفئة إي" },
    { en: "S-Class", ar: "الفئة إس" },
    { en: "GLC", ar: "جي إل سي" },
    { en: "GLE", ar: "جي إل إي" },
    { en: "GLS", ar: "جي إل إس" },
    { en: "A-Class", ar: "الفئة إيه" },
    { en: "CLA", ar: "سي إل إيه" },
    { en: "G-Class", ar: "جي كلاس" },
    { en: "AMG GT", ar: "إيه إم جي جي تي" },
    { en: "EQS", ar: "إي كيو إس" },
    { en: "EQE", ar: "إي كيو إي" },
    { en: "Maybach", ar: "مايباخ" },
  ],
  lexus: [
    { en: "ES", ar: "إي إس" },
    { en: "IS", ar: "آي إس" },
    { en: "LS", ar: "إل إس" },
    { en: "NX", ar: "إن إكس" },
    { en: "RX", ar: "آر إكس" },
    { en: "LX", ar: "إل إكس" },
    { en: "GX", ar: "جي إكس" },
    { en: "UX", ar: "يو إكس" },
    { en: "LC", ar: "إل سي" },
    { en: "RC", ar: "آر سي" },
  ],
  jeep: [
    { en: "Wrangler", ar: "رانجلر" },
    { en: "Grand Cherokee", ar: "جراند شيروكي" },
    { en: "Cherokee", ar: "شيروكي" },
    { en: "Compass", ar: "كومباس" },
    { en: "Renegade", ar: "رينيغيد" },
    { en: "Gladiator", ar: "غلاديتور" },
    { en: "Wagoneer", ar: "واغونير" },
  ],
  genesis: [
    { en: "G70", ar: "جي 70" },
    { en: "G80", ar: "جي 80" },
    { en: "G90", ar: "جي 90" },
    { en: "GV60", ar: "جي في 60" },
    { en: "GV70", ar: "جي في 70" },
    { en: "GV80", ar: "جي في 80" },
  ],
  audi: [
    { en: "A3", ar: "إيه 3" },
    { en: "A4", ar: "إيه 4" },
    { en: "A6", ar: "إيه 6" },
    { en: "A7", ar: "إيه 7" },
    { en: "A8", ar: "إيه 8" },
    { en: "Q3", ar: "كيو 3" },
    { en: "Q5", ar: "كيو 5" },
    { en: "Q7", ar: "كيو 7" },
    { en: "Q8", ar: "كيو 8" },
    { en: "e-tron", ar: "إي ترون" },
    { en: "RS5", ar: "آر إس 5" },
    { en: "RS7", ar: "آر إس 7" },
  ],
  volkswagen: [
    { en: "Tiguan", ar: "تيغوان" },
    { en: "Teramont", ar: "تيرامونت" },
    { en: "Passat", ar: "باسات" },
    { en: "Golf", ar: "غولف" },
    { en: "T-Roc", ar: "تي روك" },
    { en: "Touareg", ar: "طوارق" },
    { en: "ID.4", ar: "آي دي 4" },
    { en: "Jetta", ar: "جيتا" },
    { en: "Amarok", ar: "أماروك" },
  ],
  gmc: [
    { en: "Yukon", ar: "يوكن" },
    { en: "Sierra", ar: "سييرا" },
    { en: "Terrain", ar: "تيرين" },
    { en: "Acadia", ar: "أكاديا" },
    { en: "Canyon", ar: "كانيون" },
    { en: "Hummer EV", ar: "همر إي في" },
  ],
  mitsubishi: [
    { en: "Pajero", ar: "باجيرو" },
    { en: "Outlander", ar: "أوتلاندر" },
    { en: "Eclipse Cross", ar: "إكليبس كروس" },
    { en: "L200", ar: "إل 200" },
    { en: "ASX", ar: "إيه إس إكس" },
    { en: "Montero Sport", ar: "مونتيرو سبورت" },
  ],
  dodge: [
    { en: "Charger", ar: "تشارجر" },
    { en: "Challenger", ar: "تشالنجر" },
    { en: "Durango", ar: "دورانجو" },
    { en: "Ram 1500", ar: "رام 1500" },
    { en: "Ram 2500", ar: "رام 2500" },
  ],
  cadillac: [
    { en: "Escalade", ar: "إسكاليد" },
    { en: "CT5", ar: "سي تي 5" },
    { en: "CT4", ar: "سي تي 4" },
    { en: "XT4", ar: "إكس تي 4" },
    { en: "XT5", ar: "إكس تي 5" },
    { en: "XT6", ar: "إكس تي 6" },
    { en: "Lyriq", ar: "ليريك" },
  ],
  landrover: [
    { en: "Range Rover", ar: "رينج روفر" },
    { en: "Range Rover Sport", ar: "رينج روفر سبورت" },
    { en: "Range Rover Velar", ar: "رينج روفر فيلار" },
    { en: "Range Rover Evoque", ar: "رينج روفر إيفوك" },
    { en: "Defender", ar: "ديفندر" },
    { en: "Discovery", ar: "ديسكفري" },
    { en: "Discovery Sport", ar: "ديسكفري سبورت" },
  ],
  porsche: [
    { en: "Cayenne", ar: "كايين" },
    { en: "Macan", ar: "ماكان" },
    { en: "Panamera", ar: "باناميرا" },
    { en: "911", ar: "911" },
    { en: "Taycan", ar: "تايكان" },
    { en: "718", ar: "718" },
  ],
  other: [],
};
